### ISSUE TITLE
Percentage option in poppy

### ISSUE THREAD

**Issue by Esther-madu** [trybeans/Issues#12]
**Is your feature request related to a problem? Please describe.**
A customer complained that instead of only the fixed amount option they also want to be able to give a percentage discount to their customers.

**Describe the solution you'd like**
An option should be added to the fixed amount option which allows the retailers to reward their customer in discount percentage.

**Additional context**
![image](https://user-images.githubusercontent.com/54584431/65511672-9cb1b800-decf-11e9-886e-594159e70f3d.png)

**Comment by thetallralph** [comment]
This feature has been added.

**Comment by thetallralph** [comment]
This feature has been added.
