### ISSUE TITLE
The rules on the rewards page should link to different pages when clicked

### ISSUE THREAD

**Issue by Esther-madu** [trybeans/Issues#13]
**Is your feature request related to a problem? Please describe.**
A customer says when the customer visits the rewards program on their shop and try to click on it because it doesn't respond they are discouraged and don't engage in the program.

**Describe the solution you'd like**
A link should be added so when customers click it leads them to where they perform the action and get rewarded with points. 

**Additional context**
![image](https://user-images.githubusercontent.com/54584431/65774352-f6b3b700-e135-11e9-8e8d-48e33de2bf15.png)

**Comment by thetallralph** [comment]
This feature has been added.
Rule card on the reward page has now a button that link them to the correct action.
