### ISSUE TITLE
Lotus - Product Title Is Been Cut And Not Posted Completely on twitter

### ISSUE THREAD

**Issue by Esther-madu** [trybeans/Issues#17]
**Describe the bug**
When a customer posts a product the title of the product is not posted completely, rather it is cut and posted but not fully

**Expected behavior**
The full title should be posted as it set by the retailer and not cut.

**Screenshots**
![image](https://user-images.githubusercontent.com/54584431/70428917-d0848e80-1a77-11ea-9da7-2fa0f462f578.png)

**Comment by thetallralph** [comment]
This actually was a feature. 
Title were truncated in order to make sure we respect the character limitation of twitter
