### ISSUE TITLE
[Liana] Tierce system

### ISSUE THREAD

**Issue by ralphatbeans** [trybeans/Issues#19]
### About
A tiers system is a type of membership program where customers enjoy permanent perks and benefits depending on their rank. Unlike traditional earn & burn loyalty programs, tiered loyalty programs rank members into certain groups based on a certain metric. Each rank – or tier – is defined by a set variety of rewards, services or benefits, which increases in value as customers progress.

**What does the user want to achieve? What is their motivation?**
...
**Who are we building this for and how will they benefit?**
...
**What have customers said in the past that we would like to address with this spec?**
...

**Comment by thetallralph** [comment]
This feature has been added
