### ISSUE TITLE
Connecting to woocommerce

### ISSUE THREAD

**Issue by Esther-madu** [trybeans/Issues#2]
**### Connecting to woocommerce**
Two customers have developed this issue while trying to connect to woocommerce.

**Expected behavior**
To correct without a connection error

**Screenshots**
![image](https://user-images.githubusercontent.com/54584431/63775311-f88c1f80-c8d6-11e9-95e6-7645987e049d.png)

**Comment by thetallralph** [comment]
This issue happens because of the customer. We have written an article to help customer solve it :
https://help.trybeans.com/e-commerce-integration/woocommerce/connecting-beans-application-to-woocommerce-stores
https://help.trybeans.com/e-commerce-integration/woocommerce/having-issues-integrating
