### ISSUE TITLE
[Liana] Reward customer for product review

### ISSUE THREAD

**Issue by ralphatbeans** [trybeans/Issues#24]
**Is your feature request related to a problem? Please describe.**
Retailers would like to reward customers when they post a review on a product.

**Describe the solution you'd like**
Make the rule  "Write a product review and get x beans" available  with an integration to:
 - Shopify review 
 - Woocommerce review

**Comment by thetallralph** [comment]
This feature has been added with an integration to Judge.me 
- (Shopify & Woocommerce) 
- Woocommerce review
