### ISSUE TITLE
Lotus app selects the highest priced product among the variants

### ISSUE THREAD

**Issue by Esther-madu** [trybeans/Issues#8]
**Describe the bug**
The lotus app selects the highest priced product to be posted on social media, which is not an ideal marketing scheme, few customers have complained that it selects the highest priced product and post.

**Expected behavior**
Post the products queued no matter the price range.

**Screenshots**
![image](https://user-images.githubusercontent.com/54584431/65246208-fab45900-dae5-11e9-983b-14d217c2f5dc.png)

**Comment by thetallralph** [comment]
This issue has been solved.
Lotus will now post the variant with the lowest price by default.
